version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
#        - ./.docker/php/local.ini:/etc/php/conf.d/php.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    command: "--innodb_use_native_aio=0"
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simppay
      MYSQL_ROOT_PASSWORD: testedopic
    volumes:
      - .docker/banco:/var/lib/mysql
      - .docker/mysql/my.cnf:/etc/mysql/mycnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
